// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	APPLE_PRIVATE_KEY: string;
	APPLE_KEY_ID: string;
	APPLE_DEVELOPER_ID: string;
	CF_TEAM_NAME: string;
	CF_AUD_TAG: string;
}
