// Generated by Wrangler on Thu Sep 05 2024 06:20:30 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	APPLE_PRIVATE_KEY: string;
	APPLE_KEY_ID: string;
	APPLE_DEVELOPER_ID: string;
	CF_TEAM_NAME: string;
	CF_AUD_TAG: string;
}
