// Generated by Wrangler on Thu Aug 22 2024 07:44:51 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	APPLE_PRIVATE_KEY: string;
	APPLE_KEY_ID: string;
	APPLE_DEVELOPER_ID: string;
}
